### ISSUE TITLE
Input validering av medlemmer

### ISSUE THREAD

**Issue by pbencze** [navikt/team-catalog#7]
Input validering av rolle vises først ved lagring. Hvis man har lagt inn hele teamet er det ikke mulig å oppdatere roller individuelt. Man må nå først slette alle og så legge dem inn på nytt. 

Bør rollefeltet ha noen predifinerte tekster (eks produkteier) i tillegg til,fritekst? Det vil gjøre det enklere å lage statistikk.

**Comment by MugunthanD** [comment]
Bedre validering for roller lagt inn i produktkøen. Går snart i prod også med mulighet for å editere teammedlemmer (nå er det bare leggtil og slett som er mulig).

Hva gjelder rollefeltet så har vi diskutert det internt tidligere også. Vi landet på fritekst fordi vi ville se hva folk fylte ut litt, og vi antok også at noen ville ha flere roller, og "sære" roller... Ser ut som de fleste velger standardroller som produkteier, teamleder, utvikler osv., men noen kommer med sær-roller. Må finne en måte å få til begge på. Enig i at predefinerte tekster gir gode muligheter for statistikk. Vi avventer litt til og ser hva folk fylle rut, også tar vi nok predefinerte felter inn.

**Comment by MugunthanD** [comment]
løsning levert
